/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testGetGreeting() {
    App app = new App();
    assertEquals("Hello World!", app.getGreeting());
  }

  @Test
  public void testSum() {
    Calculator calculator = new Calculator();
    assertEquals(5, calculator.sum(2, 3));
  }

  @Test
  public void testAverage() {
    Calculator calculator = new Calculator();
    assertEquals(2.5, calculator.average(5, 2), 0.01);
  }

  @Test
  public void testSumRange() {
    Calculator calculator = new Calculator();
    assertEquals(55, calculator.sumRange(1, 10));
  }

  @Test
  public void testSumOdd() {
    Calculator calculator = new Calculator();
    assertEquals(25, calculator.sumOdd(1, 10));
  }

  @Test
  public void testSumEven() {
    Calculator calculator = new Calculator();
    assertEquals(30, calculator.sumEven(1, 10));
  }
}
